#!/usr/bin/python

import sys
import click
from kafka import KafkaConsumer


KAFKA_TOPIC = "replicator_test_kafka"

@click.command()
@click.option('--out', help='Output format: [value, key-value, meta, detailed]')
def run(out):
    consumer = KafkaConsumer(KAFKA_TOPIC,
                             bootstrap_servers='kafka:9092',
                             auto_offset_reset='smallest')
    format='detailed'

    if out:
        format=out

    try:
        for message in consumer:
            if format == 'value':
                print message.value
            elif format == 'key-value':
                print("key=%s value=%s" % (message.key,
                                          message.value))
            elif format =='meta':
                print ("%s:%d:%d" % (message.topic,
                                     message.partition,
                                     message.offset))
            else:
                print ("%s:%d:%d: key=%s value=%s" % (message.topic,
                                                      message.partition,
                                                      message.offset,
                                                      message.key,
                                                      message.value))
    except KeyboardInterrupt:
       sys.exit()

if __name__ == '__main__':
    run()

