version: '2.2'

services:
  mysql:
    image: "repl-mysql:1"
    environment:
      MYSQL_ROOT_PASSWORD: "mysqlPass"
    ports:
        - "3300:3306"  
  zookeeper:
    image: "zookeeper"
    ports:
        - "2181:2181"  
  kafka:
    image: "wurstmeister/kafka"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_CREATE_TOPICS: "replicator_test_kafka:5:1,replicator_validation:1:1"
    ports:
        - "9092:9092"  
  graphite:
    image: "hopsoft/graphite-statsd"
    ports:
        - "80:80"
        - "81:81"
        - "8125:8125"
        - "2003:2003"
    expose:
        - "2003"
