version: '2.2'

services:
  mysql:
    image: "mysql:5.7.21"
    environment:
      MYSQL_ROOT_PASSWORD: "mysqlPass"
    volumes:
      - "./resources/my.cnf:/etc/mysql/conf.d/my.cnf:ro"
      - "./resources/mysql_init_dbs.sh:/docker-entrypoint-initdb.d/mysql_init_dbs.sh:ro"
    ports:
        - "3300:3306"  
#  zookeeper:
#    image: "zookeeper"
#    ports:
#        - "2181:2181"  
  hbase:
    image: "harisekhon/hbase-dev:1.3"
    hostname: "HBASE_HOST"
    container_name: "HBASE_CONTAINER"
    ports: 
        - "2181:2181"
        - "16000:16000"
        - "16201:16201"
  graphite:
    image: "hopsoft/graphite-statsd"
    ports:
        - "80:80"
        - "81:81"
        - "8125:8125"
        - "2003:2003"
    expose:
        - "2003"
