#!/bin/bash

TEST_DIR=$1
printf "test directory: $TEST_DIR\n"

if [[ -z $TEST_DIR ]]; then
    printf "test directory is required\n"
    exit 1;
fi

#building
ECHO "STARTING UP\n"
docker-compose rm -f
docker-compose up -d --force-recreate

ECHO "sleeping\n"
sleep 10

#hbase preparation
docker exec replicatorhbase_hbase_1 sh -c "echo -e \"create_namespace 'test'\" | /hbase/bin/hbase shell -n"
docker exec replicatorhbase_hbase_1 sh -c "echo -e \"create_namespace 'schema_history'\" | /hbase/bin/hbase shell -n"

#db seeding
cat db_seed_common > $TEST_DIR/db_seed_generated
cat $TEST_DIR/db_seed >> $TEST_DIR/db_seed_generated
chmod +x $TEST_DIR/db_seed_generated
docker cp $TEST_DIR/db_seed_generated replicatorhbase_replicator_1:/replicator/db_seed
docker exec replicatorhbase_replicator_1 sh -c "/replicator/db_seed"

#replicator running
ECHO "will run replicator for 1minute"
docker exec replicatorhbase_replicator_1 sh -c "cd /replicator ; timeout 1m ./run_hbase"

#checking
printf "\n data output \n\n"
docker exec replicatorhbase_hbase_1 sh -c "echo -e \"scan 'test:hb_test_1', {VERSIONS => 20}\" | /hbase/bin/hbase shell -n"
printf "\n data output end \n\n"

#wrapping up
ECHO "WRAPPING UP"
docker-compose down
rm $TEST_DIR/db_seed_generated
