version: '3'
services:
  replicator:
    image: "replicator-runner"
  mysql:
    image: "mysql:5.6.27"
    environment:
      MYSQL_ROOT_PASSWORD: "mysqlPass"
    volumes:
      - "./my.cnf:/etc/mysql/conf.d/my.cnf:ro"
      - "./mysql_init_dbs.sh:/docker-entrypoint-initdb.d/mysql_init_dbs.sh:ro"
  zookeeper:
    image: "zookeeper"
  kafka:
    image: "wurstmeister/kafka"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "replicator_test_kafka:1:1,replicator_validation:1:1"
  graphite:
    image: "hopsoft/graphite-statsd"
    ports:
        - "80:80"
        - "8125:8125"
  grafana:
    image: "grafana/grafana"
    ports:
      - "8000:8000"

