#!/usr/bin/perl

use strict;
use warnings;

use DBI;
use Term::ReadKey;

use Data::UUID;
use Data::Dumper;

my $db       = 'test';
my $db_meta  = 'db_meta';
my $host     = 'mysql';
my $TABLE    = 'sometable';

my $data_source = "dbi:mysql:$db;host=$host";
my $data_source_active_schema = "dbi:mysql:$db" . "_active_schema;host=$host";
my $data_source_meta = "dbi:mysql:$db_meta;host=$host";

my $username = 'root';
my $pwd = "mysqlPass";

create_tables();

sub create_tables {

    my $dbh_test = DBI->connect($data_source, $username, $pwd)
              or die $DBI::errstr;

    my $dbh_test_active_schema = DBI->connect($data_source, $username, $pwd)
              or die $DBI::errstr;

    my $sql = <<EOC;
     CREATE TABLE

        sometable (

          pk_part_1         varchar(5) NOT NULL DEFAULT '',
          pk_part_2         int(11)    NOT NULL DEFAULT 0,
          randomInt         int(11)             DEFAULT NULL,
          randomVarchar     varchar(32)         DEFAULT NULL,
          PRIMARY KEY       (pk_part_1,pk_part_2),
          KEY randomVarchar (randomVarchar),
          KEY randomInt     (randomInt)

        ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
EOC

    print "reseting master...\n";
    my $ok  = $dbh_test->do("reset master");

    print "creating table in schemas (test, test_active_schema):\n" . $sql;

    my $ok1 = $dbh_test->do($sql);
    my $ok2 = $dbh_test_active_schema->do($sql);

    print "done\n";
}

