#!/usr/bin/perl

use strict;
use warnings;

use DBI;
use Term::ReadKey;

use Data::UUID;
use Data::Dumper;

my $db       = 'test';
my $host     = 'mysql';
my $TABLE    = 'sometable';

my $data_source = "dbi:mysql:$db;host=$host";

my $username = 'root';
my $pwd      = "mysqlPass";

my $BATCHES = 1000;

my $batch_no = 0;

while ($batch_no++ <= $BATCHES) {
    insert_random_records(1000);
}

sub insert_random_records {

    my $nr_rows = shift;

    my $dbh = DBI->connect($data_source, $username, $pwd)
              or die $DBI::errstr;

    my @chars = ("A".."Z", "a".."z", " ");
    my @values = ();
    my $nr_rows_to_insert = $nr_rows;
    for (1 .. $nr_rows_to_insert) {
        my $string; # pk_part1
        my $number; # pk_part2
        my $int;    # randomInt
        my $text;   # randomVarchar
        $string .= $chars[rand @chars] for 1..5;
        $number  = int(5000000 * rand);
        $int     = int(1000000 * rand);
        $text   .= $chars[rand @chars] for 1..20;
        push @values , [$string, $number, $int, $text];
    }

    my $columns = "(pk_part_1, pk_part_2, randomInt, randomVarchar)";

    my $values = "";
    while (my $entry = shift @values) {
       $values .= "(";
       $values .= join(",", map {"\'" . $_ . "\'"} @$entry);
       if(@values) {
           $values .= "),\n";
       }
       else {
           $values .= ")\n";
       }
    }

    my $sql_insert = qq{
        insert into $TABLE
            $columns
        VALUES
            $values
    };

    print $sql_insert;

    my $result = $dbh->do($sql_insert);

}

